on: [push]
jobs:
  push-to-yc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to YC
        run: docker login -u ${{ secrets.YC_USERNAME }} -p ${{ secrets.YC_PASSWORD }}  cr.yandex

      - name: Build image
        run: docker build . -t catgpt

      - name: Push image
        run: docker tag catgpt cr.yandex/crp540fjdpqs889e0isn/catgpt && docker push cr.yandex/crp540fjdpqs889e0isn/catgpt